version: "3.8"

services:
  bill_split_api:
    container_name: bill_split_api_local
    build:
      context: ./../backend/
      dockerfile: ./../deploy/docker/Api.Dockerfile
    pull_policy: always
    restart: always
    environment:
      # Server - Framework settings
      - DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=false
      - ASPNETCORE_URLS=http://+:80;
      - ASPNETCORE_ENVIRONMENT=Production
      # Server - Application settings
      - ConnectionStrings__ApplicationContext=host=postgresql;port=5432;database=bill_split_db;username=postgres;password=Pass@word
      - ConnectionStrings__RedisConnectionString=redis:6379,password=Pass@word,abortConnect=false
    ports:
      - "5003:80"
    depends_on:
      - postgresql
      - redis

  postgresql:
    container_name: postgresql_local
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Pass@word
      - POSTGRES_DB=bill_split_db
    ports:
      - "8002:5432"
    volumes:
      - ./local/postgresql_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=Pass@word
      - REDIS_PORT=6379
      - REDIS_DATABASES=1
