version: "3.8"

services:
  bill_split_api:
    container_name: bill_split_api
    image: durneacalin/billsplit:latest
    build:
      context: ./../
      dockerfile: ./deploy/docker/Api.Dockerfile
    pull_policy: always
    restart: always
    environment:
      # Server - Framework settings
      - DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=false
      - ASPNETCORE_URLS=http://+:80;
      - ASPNETCORE_ENVIRONMENT=Production
      # Server - Application settings
      - ConnectionStrings__ApplicationContext=host=postgresql;port=5432;database=${POSTGRES_DATABASE};username=${POSTGRES_USER};password=${POSTGRES_PASSWORD}
      - ConnectionStrings__RedisConnectionString=redis:6379,password=${REDIS_PASSWORD},abortConnect=false
    ports:
      - "5002:80"
    depends_on:
      - postgresql
      - redis

  postgresql:
    container_name: postgresql
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    ports:
      - "8001:5432"
    volumes:
      - ./production/postgresql_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PORT=6379
      - REDIS_DATABASES=1